spring:
  data:
    mongodb:
      uri: "mongodb+srv://userApp:Fx66ttw9hxBXt8cQ@cluster0.opfry6k.mongodb.net/booking_ai?retryWrites=true&w=majority&appName=Cluster0"

#  datasource:
#    username: aplicaciones
#    password: OperativaClientes2014
#    url: "jdbc:mysql://104.154.251.174:3306/red_amarilla_desarrollo?useSSL=false"
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 15000
#      idle-timeout: 300000
#      max-lifetime: 900000
#  jpa:
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#        event:
#          merge:
#            entity_copy_observer: allow
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        dialect: org.hibernate.dialect.MySQL55Dialect
#        jdbc:
#          batch_size: 20
#          lob:
#            non_contextual_creation: true
#          cache:
#            use_query_cache: true
#            use_second_level_cache: true
#            use_structured_entries: true
#            use_minimal_puts: true
#        temp:
#          use_jdbc_metadata_defaults: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  redis:
#    password: xWVNpzhtMJB94xlwm3m4gf5R12L5r69R
#    host: redis-18989.c279.us-central1-1.gce.cloud.redislabs.com
#    port: 18989
#    timeout: 60000
#    database: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    lettuce:
#      shutdown-timeout: 36000
#      pool:
#        max-active: 256
#        max-idle: 128
#        min-idle: 32

server:
  port : 9001
  servlet:
    context-path: ${application.booking_ai.api.path}
management:
  endpoints:
    web:
      exposure:
        include: '*'
rest:
  retry: 2
  username: "central-appengine"
  password: "hyRRp474pUSpWY"
  adapter:
    url-geo-reverse-here: "https://revgeocode.search.hereapi.com/v1/revgeocode"
    url-geo-reverse-google: "https://maps.googleapis.com/maps/api/geocode/json"
    key-reverse-google: "AIzaSyAk0flSOrPQipfWxdBitD9unTVMGVMySGQ"
    apiKey-reverse-here: "j94Vg5BknziREWOsuh6UMAdZTafwmuq39zf35_H9pUg"
    micro-bloqueo: "http://appusuario.com/api/bloq/find.bloq/"
    autenticar-kubernetes: "http://appusuario.com/api/autenticacion"
