################################# Deployment  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-servicios-usuario-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-servicios-usuario-dev
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ms-servicios-usuario-dev
        version: v1
    spec:
      # [START secret-1]
      volumes:
        - name: service-account-endpoint-creds
          configMap:
            name: cred-endpoint-config-map
          #- name: service-account-pubsub-creds
          # configMap:
          #  name: cred-pubsub-config-map
      # [END secret-1]
      # [START service]
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
              "--http_port", "8080",
              "--backend", "127.0.0.1:9001",
              "--service", "servicios-usuario-api-v1.endpoints.red-amarilla.cloud.goog",
              "--rollout_strategy", "managed",
              "--service_account_key", "/data/service-account-endpoint-creds.json",
          ]
          # [END service]
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 100Mi
          # [START secret-2]
          volumeMounts:
            - mountPath: /data
              name: service-account-endpoint-creds
              readOnly: true
          # [END secret-2]
        - name: ms-tarificador
          image: IMAGETAG
            #args: [
          # "--service_account_key", "/data/service-account-pubsub-creds.json",
          #]
          ports:
            - containerPort: 9001
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 900Mi
            requests:
              cpu: 500m
              memory: 550Mi
            #volumeMounts:
            # - mountPath: /data
            #  name: service-account-pubsub-creds
            #  readOnly: true
      #imagePullSecrets:
      #- name: joseadelarosa-terpelaccount-pull-secret
---
################################# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-servicios-usuario-dev
  name: ms-servicios-usuario-dev
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: ms-servicios-usuario-dev
  type: ClusterIP
---
################################# Service
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: ms-servicios-usuario-dev
  labels:
    app: ms-servicios-usuario-dev
    version: v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: ms-servicios-usuario-dev
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
---
